#
# Software Name : towards5gs-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Abderaouf KHICHANE, Ilhem FAJJARI, Ayoub BOUSSELMI
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
# Default values for Open5GS UPF chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


global:
  projectName: open5gs
  uesubnet: 10.45.0.0/16
#Global network parametes
  n4network:
    name: n4network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n3network:
    name: n3network
    type: ipvlan
    masterIf: eth0
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n6network:
    name: n6network
    type: ipvlan
    masterIf: eth1
    subnetIP: 10.100.100.0
    cidr: 24
    gatewayIP: 10.100.100.1
    excludeIP: 10.100.100.254

upf:
  name: upf
  replicaCount: 1
  image:
    name: towards5gs/open5gs-upf
    pullPolicy: Always
  metricService:
    type: ClusterIP
    port: 9090
  volume:
    mount: /open5gs/install/etc

  # network paramters
  n3if:  # GTP-U
    ipAddress: 10.100.50.233
  n4if:  # PFCP
    ipAddress: 10.100.50.241
  n6if:  # DN
    ipAddress: 10.100.100.12

  podAnnotations: {}
    # additional annotations
  imagePullSecrets: []
  podSecurityContext: {}
  securityContext:
    privileged: true
    capabilities:
      add: ["NET_ADMIN"]
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  readinessProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    timeoutSeconds: 1
    failureThreshold:  40
    successThreshold: 1
  livenessProbe:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  configuration:

    global: |-
      global:
        max:
          ue: 1024

    upf: |-
      session:
        - gateway: 10.45.0.1
          subnet: 10.45.0.0/16
        - gateway: '2001:db8:cafe::1'
          subnet: '2001:db8:cafe::/48'

    logger: |-
      level: info
